# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable
  - dev

stages:
  - analyze_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-warnings .

cache:
  directories:
  - .dart_tool/build
