# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable
  - dev

stages:
  - analyze_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-warnings .
  - build:
    - group:
      - command: pub run build_runner build
    - group:
      - command: pub run build_runner build --release

cache:
  directories:
  - .dart_tool/build
